### PR TITLE
Fixed stage, since it crashed

### PR DESCRIPTION
**Pull request by LEVIXDDLMAO**

### CODE REVIEW

**Comment by UNSTOP4BLE** [comment]
wha

**Comment by LEVIXDDLMAO** [comment]
Dude On html it crashes i fixed it

**Comment by UNSTOP4BLE** [comment]
?? it literally works fine lmao, i just everything from the original mod

**Comment by UNSTOP4BLE** [comment]
also, why did you change the jsons? the stages are hardcoded

**Comment by LEVIXDDLMAO** [comment]
when it was ported to normal html5 the stage made the game crashed

**Comment by UNSTOP4BLE** [comment]
normal html5?

**Comment by LEVIXDDLMAO** [comment]
yeah, since this version is supporting moblie-html5
 for norml html5 stage it crashed my game and i looked in to it and found that was the reason why

**Comment by UNSTOP4BLE** [comment]
what does normal html5 mean?

**Comment by LEVIXDDLMAO** [comment]
no moblie shit

**Comment by UNSTOP4BLE** [comment]
oh, this is meant to be ran only on psych 0.5.1

**Comment by LEVIXDDLMAO** [comment]
it is , Something was breaking the stages

**Comment by UNSTOP4BLE** [comment]
oh, alright then

**Comment by LEVIXDDLMAO** [comment]
but now it should work! Im gald to help with anything

**Comment by UNSTOP4BLE** [comment]
nice, thanks

**Comment by LEVIXDDLMAO** [comment]
np!

**Pull request merged**
